---
- hosts: jenkinsslave
  become: true 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes 

  - name: install java 
    apt: 
      name: openjdk-17-jre
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt 
      remote_src: yes

  - name: install docker 
    apt: 
      name: docker.io 
      state: present

  - name: change file permissions
    file: 
      path: /var/run/docker.sock
      state: file 
      mode: 0777

  - name: start docker services 
    service: 
      name: docker 
      state: started 
      
  - name: start docker on boot time 
    service: 
      name: docker 
      enabled: yes 

